INFO (theano.gof.compilelock): Waiting for existing lock by unknown process (I am process '192363')
INFO (theano.gof.compilelock): To manually release the lock, delete /home/jb6504/.theano/compiledir_Linux-3.10-el7.x86_64-x86_64-with-centos-7.3.1611-Core-x86_64-2.7.12-64/lock_dir
25.04.2018 18:14:51 INFO    Hi! How are you today?
25.04.2018 18:14:51 INFO    Startup options:
25.04.2018 18:14:51 INFO      Algorithm:                     histo
25.04.2018 18:14:51 INFO      Point by point:                False
25.04.2018 18:14:51 INFO      Morphing-aware mode:           False
25.04.2018 18:14:51 INFO      Smeared data:                  False
25.04.2018 18:14:51 INFO      Training sample:               baseline
25.04.2018 18:14:51 INFO      alpha:                         None
25.04.2018 18:14:51 INFO      Histogram / AFC X indices:     [1, 41]
25.04.2018 18:14:51 INFO      AFC epsilon:                   None
25.04.2018 18:14:51 INFO      Denominator theta:             False
25.04.2018 18:14:51 INFO      Neyman construction toys:      2
25.04.2018 18:14:51 INFO      Training sample size limit:    None
25.04.2018 18:14:51 INFO      Other options:                 ['asymmetricbinning']
25.04.2018 18:14:51 INFO      Base directory:                /home/jb6504/higgs_inference
25.04.2018 18:14:51 INFO      ML-based strategies available: False
25.04.2018 18:14:51 INFO    Starting histogram-based inference
25.04.2018 18:14:51 INFO    Settings:
25.04.2018 18:14:51 INFO      Statistics:              x [1, 41]
25.04.2018 18:14:51 INFO      Binning:                 (array([     0.,     48.,     58.,     67.,     75.,     83.,     91.,
          100.,    109.,    119.,    130.,    141.,    155.,    172.,
          193.,    221.,    260.,    325.,    462.,  14000.]), array([ 0.        ,  0.31415927,  0.62831853,  0.9424778 ,  1.25663706,
        1.57079633,  1.88495559,  2.19911486,  2.51327412,  2.82743339,
        3.14159265]))
Traceback (most recent call last):
  File "experiments.py", line 118, in <module>
    options=args.options)
  File "/home/jb6504/higgs_inference/higgs_inference/strategies/histograms.py", line 194, in histo_inference
    t) + input_filename_addition + new_sample_prefix + '.npy')
  File "/share/apps/python/2.7.12/intel/lib/python2.7/site-packages/numpy-1.11.2-py2.7-linux-x86_64.egg/numpy/lib/npyio.py", line 362, in load
    fid = open(file, "rb")
IOError: [Errno 2] No such file or directory: '/scratch/jb6504/higgs_inference/data/unweighted_events/point_by_point/X_train_point_by_point_0_denom2.npy'
